elasticsearch: upgrade to 0.90.2 and upstartize
Upgrade the elasticsearch build to version 0.90.2 (current latest) and
debhelperize the build.

Also add an elasticsearch.upstart and elasticsearch.default file for
cleaner process management.

diff --git a/pkg/elasticsearch/debian/elasticsearch.postinst b/pkg/elasticsearch/debian/elasticsearch.postinst
--- a/pkg/elasticsearch/debian/elasticsearch.postinst
+++ b/pkg/elasticsearch/debian/elasticsearch.postinst
@@ -1,40 +1,40 @@
 #!/bin/sh
+# postinst script for #PACKAGE#
+#
+# see: dh_installdeb(1)
+
 set -e
+
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
 
 case "$1" in
     configure)
-	[ -f /etc/default/elasticsearch ] && . /etc/default/elasticsearch
-	[ -z "$ES_USER" ] && ES_USER="elasticsearch"
-	[ -z "$ES_GROUP" ] && ES_GROUP="elasticsearch"
-	if ! getent group "$ES_GROUP" > /dev/null 2>&1 ; then
-	    addgroup --system "$ES_GROUP" --quiet
-	fi
-	if ! id $ES_USER > /dev/null 2>&1 ; then
-	    adduser --system --home /usr/share/elasticsearch --no-create-home \
-		--ingroup "$ES_GROUP" --disabled-password --shell /bin/false \
-		"$ES_USER"
-	fi
+        adduser --system --group --no-create-home --quiet elasticsearch || true
+    ;;
 
-	# Set user permissions on /var/log/elasticsearch and /var/lib/elasticsearch
-	mkdir -p /var/log/elasticsearch /var/lib/elasticsearch
-	chown -R $ES_USER:$ES_GROUP /var/log/elasticsearch /var/lib/elasticsearch
-	chmod 755 /var/log/elasticsearch /var/lib/elasticsearch
+    abort-upgrade|abort-remove|abort-deconfigure)
+    ;;
 
-	# configuration files should not be modifiable by elasticsearch user, as this can be a security issue
-	chown -Rh root:root /etc/elasticsearch/*
-	chmod 755 /etc/elasticsearch
-	chmod 644 /etc/elasticsearch/*
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
     ;;
 esac
 
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
 
-if [ -x "/etc/init.d/elasticsearch" ]; then
-	update-rc.d elasticsearch defaults 95 10 >/dev/null
-	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
-		invoke-rc.d elasticsearch start || true
-	else
-		/etc/init.d/elasticsearch start || true
-	fi
-fi
+#DEBHELPER#
 
-
+exit 0
